language: python
python:
    - "2.7"

virtualenv:
    system_site_packages: true
before_install:
    - sudo apt-get update -qq
    - sudo apt-get install -y gfortran libopenblas-dev liblapack-dev
    - sudo apt-get install -y python-numpy
    - sudo apt-get install -y python-scipy
install:
    - pip install future 
    - pip install coverage 
script:
    - nosetests